name: Docker

on:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling repo
        uses: actions/checkout@v2
      - name: Building latest image
        run: docker build -t image:latest .
      - name: Adding additional tags
        run: |
          REPO=$(cut -d/ -f2 <<< $GITHUB_REPOSITORY)
          DATE=$(date -Idate)
          docker tag image:latest docker.pkg.github.com/$GITHUB_REPOSITORY/$REPO-web:latest
          docker tag image:latest docker.pkg.github.com/$GITHUB_REPOSITORY/$REPO-web:$GITHUB_SHA
          docker tag image:latest docker.pkg.github.com/$GITHUB_REPOSITORY/$REPO-web:$DATE
      - name: Loging in
        run: |
          USER=$(cut -d/ -f1 <<< $GITHUB_REPOSITORY)
          docker login docker.pkg.github.com -u $USER -p ${{ secrets.GITHUB_TOKEN }}
      - name: Pushing image
        run: |
          REPO=$(cut -d/ -f2 <<< $GITHUB_REPOSITORY)
          DATE=$(date -Idate)
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$REPO-web:latest
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$REPO-web:$GITHUB_SHA
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$REPO-web:$DATE
      - name: Writing stack config file
        run: |
          DATE=$(date -Idate)
          echo '${{ secrets.DOCKER_STACK_YAML }}' > stack.yaml
          sed -i "s/latest/$DATE/g" stack.yaml
      - name: Deploying new version
        uses: scotow/docker-ssh-action@master
        with:
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_ssh_public_key: ${{ secrets.REMOTE_SSH_PUBLIC_KEY }}
          remote_ssh_proto: ${{ secrets.REMOTE_SSH_PROTO }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: stack deploy -c stack.yaml --with-registry-auth gitfolio